#!/usr/bin/env sh
# generated from catkin/python/catkin/environment_cache.py

# based on a snapshot of the environment before and after calling the setup script
# it emulates the modifications of the setup script without recurring computations

# new environment variables

# modified environment variables
export CMAKE_PREFIX_PATH='/home/pe/ws_rockpicker/devel_isolated/moveit_calibration_gui:/home/pe/ws_rockpicker/devel_isolated/moveit_calibration_plugins:/home/pe/ws_rockpicker/devel_isolated/realsense_ting_controller:/home/pe/ws_rockpicker/devel_isolated/wsg_gripper:/home/pe/ws_rockpicker/devel_isolated/ur_calibration:/home/pe/ws_rockpicker/devel_isolated/ur_robot_driver:/home/pe/ws_rockpicker/devel_isolated/ur_kinematics:/home/pe/ws_rockpicker/devel_isolated/ur_gazebo:/home/pe/ws_rockpicker/devel_isolated/ur_description:/home/pe/ws_rockpicker/devel_isolated/ur_dashboard_msgs:/home/pe/ws_rockpicker/devel_isolated/ur5e_moveit_config:/home/pe/ws_rockpicker/devel_isolated/ur5_moveit_config:/home/pe/ws_rockpicker/devel_isolated/ur5_module:/home/pe/ws_rockpicker/devel_isolated/ur3e_moveit_config:/home/pe/ws_rockpicker/devel_isolated/ur3_moveit_config:/home/pe/ws_rockpicker/devel_isolated/ur16e_moveit_config:/home/pe/ws_rockpicker/devel_isolated/ur10e_moveit_config:/home/pe/ws_rockpicker/devel_isolated/ur10_moveit_config:/home/pe/ws_rockpicker/devel_isolated/universal_robots:/home/pe/ws_rockpicker/devel_isolated/moveit_tutorials:/opt/ros/noetic:/home/pe/ws_rockpicker/devel_isolated/ur_client_library:/home/pe/ws_rockpicker/devel_isolated/ur_client_library'
export LD_LIBRARY_PATH='/home/pe/ws_rockpicker/devel_isolated/moveit_calibration_gui/lib:/home/pe/ws_rockpicker/devel_isolated/moveit_calibration_plugins/lib:/home/pe/ws_rockpicker/devel_isolated/realsense_ting_controller/lib:/home/pe/ws_rockpicker/devel_isolated/wsg_gripper/lib:/home/pe/ws_rockpicker/devel_isolated/ur_calibration/lib:/home/pe/ws_rockpicker/devel_isolated/ur_robot_driver/lib:/home/pe/ws_rockpicker/devel_isolated/ur_kinematics/lib:/home/pe/ws_rockpicker/devel_isolated/ur_gazebo/lib:/home/pe/ws_rockpicker/devel_isolated/ur_description/lib:/home/pe/ws_rockpicker/devel_isolated/ur_dashboard_msgs/lib:/home/pe/ws_rockpicker/devel_isolated/ur5e_moveit_config/lib:/home/pe/ws_rockpicker/devel_isolated/ur5_moveit_config/lib:/home/pe/ws_rockpicker/devel_isolated/ur5_module/lib:/home/pe/ws_rockpicker/devel_isolated/ur3e_moveit_config/lib:/home/pe/ws_rockpicker/devel_isolated/ur3_moveit_config/lib:/home/pe/ws_rockpicker/devel_isolated/ur16e_moveit_config/lib:/home/pe/ws_rockpicker/devel_isolated/ur10e_moveit_config/lib:/home/pe/ws_rockpicker/devel_isolated/ur10_moveit_config/lib:/home/pe/ws_rockpicker/devel_isolated/moveit_tutorials/lib:/opt/ros/noetic/lib:/opt/ros/noetic/lib/x86_64-linux-gnu:/home/pe/ws_rockpicker/devel_isolated/ur_client_library/lib:/home/pe/ws_rockpicker/devel_isolated/ur_client_library/lib/x86_64-linux-gnu:/home/pe/ws_rockpicker/devel_isolated/ur_client_library/lib'
export PATH='/opt/ros/noetic/bin:/home/pe/ws_rockpicker/devel_isolated/ur_client_library/bin:/home/pe/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'
export PKG_CONFIG_PATH='/home/pe/ws_rockpicker/devel_isolated/moveit_calibration_gui/lib/pkgconfig:/home/pe/ws_rockpicker/devel_isolated/moveit_calibration_plugins/lib/pkgconfig:/home/pe/ws_rockpicker/devel_isolated/realsense_ting_controller/lib/pkgconfig:/home/pe/ws_rockpicker/devel_isolated/wsg_gripper/lib/pkgconfig:/home/pe/ws_rockpicker/devel_isolated/ur_calibration/lib/pkgconfig:/home/pe/ws_rockpicker/devel_isolated/ur_robot_driver/lib/pkgconfig:/home/pe/ws_rockpicker/devel_isolated/ur_kinematics/lib/pkgconfig:/home/pe/ws_rockpicker/devel_isolated/ur_gazebo/lib/pkgconfig:/home/pe/ws_rockpicker/devel_isolated/ur_description/lib/pkgconfig:/home/pe/ws_rockpicker/devel_isolated/ur_dashboard_msgs/lib/pkgconfig:/home/pe/ws_rockpicker/devel_isolated/ur5e_moveit_config/lib/pkgconfig:/home/pe/ws_rockpicker/devel_isolated/ur5_moveit_config/lib/pkgconfig:/home/pe/ws_rockpicker/devel_isolated/ur5_module/lib/pkgconfig:/home/pe/ws_rockpicker/devel_isolated/ur3e_moveit_config/lib/pkgconfig:/home/pe/ws_rockpicker/devel_isolated/ur3_moveit_config/lib/pkgconfig:/home/pe/ws_rockpicker/devel_isolated/ur16e_moveit_config/lib/pkgconfig:/home/pe/ws_rockpicker/devel_isolated/ur10e_moveit_config/lib/pkgconfig:/home/pe/ws_rockpicker/devel_isolated/ur10_moveit_config/lib/pkgconfig:/home/pe/ws_rockpicker/devel_isolated/moveit_tutorials/lib/pkgconfig:/opt/ros/noetic/lib/pkgconfig:/opt/ros/noetic/lib/x86_64-linux-gnu/pkgconfig:/home/pe/ws_rockpicker/devel_isolated/ur_client_library/lib/pkgconfig:/home/pe/ws_rockpicker/devel_isolated/ur_client_library/lib/x86_64-linux-gnu/pkgconfig'
export PYTHONPATH='/home/pe/ws_rockpicker/devel_isolated/realsense_ting_controller/lib/python3/dist-packages:/home/pe/ws_rockpicker/devel_isolated/wsg_gripper/lib/python3/dist-packages:/home/pe/ws_rockpicker/devel_isolated/ur_kinematics/lib/python3/dist-packages:/home/pe/ws_rockpicker/devel_isolated/ur_dashboard_msgs/lib/python3/dist-packages:/opt/ros/noetic/lib/python3/dist-packages:/home/pe/ws_rockpicker/devel_isolated/ur_client_library/lib/python3/dist-packages'