set(_CATKIN_CURRENT_PACKAGE "ur5_module")
set(ur5_module_VERSION "0.0.0")
set(ur5_module_MAINTAINER "pe <pe@todo.todo>")
set(ur5_module_PACKAGE_FORMAT "2")
set(ur5_module_BUILD_DEPENDS "message_generation" "moveit_commander" "rospy")
set(ur5_module_BUILD_EXPORT_DEPENDS "moveit_commander" "rospy")
set(ur5_module_BUILDTOOL_DEPENDS "catkin")
set(ur5_module_BUILDTOOL_EXPORT_DEPENDS )
set(ur5_module_EXEC_DEPENDS "message_runtime" "moveit_commander" "rospy")
set(ur5_module_RUN_DEPENDS "message_runtime" "moveit_commander" "rospy")
set(ur5_module_TEST_DEPENDS )
set(ur5_module_DOC_DEPENDS )
set(ur5_module_URL_WEBSITE "")
set(ur5_module_URL_BUGTRACKER "")
set(ur5_module_URL_REPOSITORY "")
set(ur5_module_DEPRECATED "")