set(_CATKIN_CURRENT_PACKAGE "wsg_gripper")
set(wsg_gripper_VERSION "0.0.0")
set(wsg_gripper_MAINTAINER "pe <pe@todo.todo>")
set(wsg_gripper_PACKAGE_FORMAT "2")
set(wsg_gripper_BUILD_DEPENDS "message_generation" "rospy" "std_msgs")
set(wsg_gripper_BUILD_EXPORT_DEPENDS "rospy" "std_msgs")
set(wsg_gripper_BUILDTOOL_DEPENDS "catkin")
set(wsg_gripper_BUILDTOOL_EXPORT_DEPENDS )
set(wsg_gripper_EXEC_DEPENDS "message_runtime" "rospy" "std_msgs")
set(wsg_gripper_RUN_DEPENDS "message_runtime" "rospy" "std_msgs")
set(wsg_gripper_TEST_DEPENDS )
set(wsg_gripper_DOC_DEPENDS )
set(wsg_gripper_URL_WEBSITE "")
set(wsg_gripper_URL_BUGTRACKER "")
set(wsg_gripper_URL_REPOSITORY "")
set(wsg_gripper_DEPRECATED "")