// Generated by gencpp from file wsg_gripper/GripperCommand.msg
// DO NOT EDIT!


#ifndef WSG_GRIPPER_MESSAGE_GRIPPERCOMMAND_H
#define WSG_GRIPPER_MESSAGE_GRIPPERCOMMAND_H

#include <ros/service_traits.h>


#include <wsg_gripper/GripperCommandRequest.h>
#include <wsg_gripper/GripperCommandResponse.h>


namespace wsg_gripper
{

struct GripperCommand
{

typedef GripperCommandRequest Request;
typedef GripperCommandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GripperCommand
} // namespace wsg_gripper


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wsg_gripper::GripperCommand > {
  static const char* value()
  {
    return "22c7c465d64c7e74c6ae22029c7ca150";
  }

  static const char* value(const ::wsg_gripper::GripperCommand&) { return value(); }
};

template<>
struct DataType< ::wsg_gripper::GripperCommand > {
  static const char* value()
  {
    return "wsg_gripper/GripperCommand";
  }

  static const char* value(const ::wsg_gripper::GripperCommand&) { return value(); }
};


// service_traits::MD5Sum< ::wsg_gripper::GripperCommandRequest> should match
// service_traits::MD5Sum< ::wsg_gripper::GripperCommand >
template<>
struct MD5Sum< ::wsg_gripper::GripperCommandRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wsg_gripper::GripperCommand >::value();
  }
  static const char* value(const ::wsg_gripper::GripperCommandRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wsg_gripper::GripperCommandRequest> should match
// service_traits::DataType< ::wsg_gripper::GripperCommand >
template<>
struct DataType< ::wsg_gripper::GripperCommandRequest>
{
  static const char* value()
  {
    return DataType< ::wsg_gripper::GripperCommand >::value();
  }
  static const char* value(const ::wsg_gripper::GripperCommandRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wsg_gripper::GripperCommandResponse> should match
// service_traits::MD5Sum< ::wsg_gripper::GripperCommand >
template<>
struct MD5Sum< ::wsg_gripper::GripperCommandResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wsg_gripper::GripperCommand >::value();
  }
  static const char* value(const ::wsg_gripper::GripperCommandResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wsg_gripper::GripperCommandResponse> should match
// service_traits::DataType< ::wsg_gripper::GripperCommand >
template<>
struct DataType< ::wsg_gripper::GripperCommandResponse>
{
  static const char* value()
  {
    return DataType< ::wsg_gripper::GripperCommand >::value();
  }
  static const char* value(const ::wsg_gripper::GripperCommandResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WSG_GRIPPER_MESSAGE_GRIPPERCOMMAND_H
