// Generated by gencpp from file wsg_gripper/GripperCommandResponse.msg
// DO NOT EDIT!


#ifndef WSG_GRIPPER_MESSAGE_GRIPPERCOMMANDRESPONSE_H
#define WSG_GRIPPER_MESSAGE_GRIPPERCOMMANDRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace wsg_gripper
{
template <class ContainerAllocator>
struct GripperCommandResponse_
{
  typedef GripperCommandResponse_<ContainerAllocator> Type;

  GripperCommandResponse_()
    : response()  {
    }
  GripperCommandResponse_(const ContainerAllocator& _alloc)
    : response(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _response_type;
  _response_type response;





  typedef boost::shared_ptr< ::wsg_gripper::GripperCommandResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wsg_gripper::GripperCommandResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GripperCommandResponse_

typedef ::wsg_gripper::GripperCommandResponse_<std::allocator<void> > GripperCommandResponse;

typedef boost::shared_ptr< ::wsg_gripper::GripperCommandResponse > GripperCommandResponsePtr;
typedef boost::shared_ptr< ::wsg_gripper::GripperCommandResponse const> GripperCommandResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wsg_gripper::GripperCommandResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wsg_gripper::GripperCommandResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::wsg_gripper::GripperCommandResponse_<ContainerAllocator1> & lhs, const ::wsg_gripper::GripperCommandResponse_<ContainerAllocator2> & rhs)
{
  return lhs.response == rhs.response;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::wsg_gripper::GripperCommandResponse_<ContainerAllocator1> & lhs, const ::wsg_gripper::GripperCommandResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace wsg_gripper

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::wsg_gripper::GripperCommandResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wsg_gripper::GripperCommandResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wsg_gripper::GripperCommandResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wsg_gripper::GripperCommandResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wsg_gripper::GripperCommandResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wsg_gripper::GripperCommandResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wsg_gripper::GripperCommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6de314e2dc76fbff2b6244a6ad70b68d";
  }

  static const char* value(const ::wsg_gripper::GripperCommandResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6de314e2dc76fbffULL;
  static const uint64_t static_value2 = 0x2b6244a6ad70b68dULL;
};

template<class ContainerAllocator>
struct DataType< ::wsg_gripper::GripperCommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wsg_gripper/GripperCommandResponse";
  }

  static const char* value(const ::wsg_gripper::GripperCommandResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wsg_gripper::GripperCommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string response\n"
;
  }

  static const char* value(const ::wsg_gripper::GripperCommandResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wsg_gripper::GripperCommandResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.response);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GripperCommandResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wsg_gripper::GripperCommandResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wsg_gripper::GripperCommandResponse_<ContainerAllocator>& v)
  {
    s << indent << "response: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.response);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WSG_GRIPPER_MESSAGE_GRIPPERCOMMANDRESPONSE_H
