// Generated by gencpp from file wsg_gripper/GripperCommandRequest.msg
// DO NOT EDIT!


#ifndef WSG_GRIPPER_MESSAGE_GRIPPERCOMMANDREQUEST_H
#define WSG_GRIPPER_MESSAGE_GRIPPERCOMMANDREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace wsg_gripper
{
template <class ContainerAllocator>
struct GripperCommandRequest_
{
  typedef GripperCommandRequest_<ContainerAllocator> Type;

  GripperCommandRequest_()
    : command()  {
    }
  GripperCommandRequest_(const ContainerAllocator& _alloc)
    : command(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _command_type;
  _command_type command;





  typedef boost::shared_ptr< ::wsg_gripper::GripperCommandRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wsg_gripper::GripperCommandRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GripperCommandRequest_

typedef ::wsg_gripper::GripperCommandRequest_<std::allocator<void> > GripperCommandRequest;

typedef boost::shared_ptr< ::wsg_gripper::GripperCommandRequest > GripperCommandRequestPtr;
typedef boost::shared_ptr< ::wsg_gripper::GripperCommandRequest const> GripperCommandRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wsg_gripper::GripperCommandRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wsg_gripper::GripperCommandRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::wsg_gripper::GripperCommandRequest_<ContainerAllocator1> & lhs, const ::wsg_gripper::GripperCommandRequest_<ContainerAllocator2> & rhs)
{
  return lhs.command == rhs.command;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::wsg_gripper::GripperCommandRequest_<ContainerAllocator1> & lhs, const ::wsg_gripper::GripperCommandRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace wsg_gripper

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::wsg_gripper::GripperCommandRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wsg_gripper::GripperCommandRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wsg_gripper::GripperCommandRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wsg_gripper::GripperCommandRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wsg_gripper::GripperCommandRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wsg_gripper::GripperCommandRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wsg_gripper::GripperCommandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cba5e21e920a3a2b7b375cb65b64cdea";
  }

  static const char* value(const ::wsg_gripper::GripperCommandRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcba5e21e920a3a2bULL;
  static const uint64_t static_value2 = 0x7b375cb65b64cdeaULL;
};

template<class ContainerAllocator>
struct DataType< ::wsg_gripper::GripperCommandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wsg_gripper/GripperCommandRequest";
  }

  static const char* value(const ::wsg_gripper::GripperCommandRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wsg_gripper::GripperCommandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string command\n"
;
  }

  static const char* value(const ::wsg_gripper::GripperCommandRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wsg_gripper::GripperCommandRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GripperCommandRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wsg_gripper::GripperCommandRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wsg_gripper::GripperCommandRequest_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.command);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WSG_GRIPPER_MESSAGE_GRIPPERCOMMANDREQUEST_H
