set(_CATKIN_CURRENT_PACKAGE "realsense_ting_controller")
set(realsense_ting_controller_VERSION "0.0.0")
set(realsense_ting_controller_MAINTAINER "linux <linux@todo.todo>")
set(realsense_ting_controller_PACKAGE_FORMAT "2")
set(realsense_ting_controller_BUILD_DEPENDS "message_generation" "realsense2_camera" "rospy" "cv_bridge" "opencv2" "sensor_msgs" "std_msgs")
set(realsense_ting_controller_BUILD_EXPORT_DEPENDS "realsense2_camera" "rospy" "cv_bridge" "opencv2" "sensor_msgs" "std_msgs")
set(realsense_ting_controller_BUILDTOOL_DEPENDS "catkin")
set(realsense_ting_controller_BUILDTOOL_EXPORT_DEPENDS )
set(realsense_ting_controller_EXEC_DEPENDS "message_runtime" "realsense2_camera" "rospy" "cv_bridge" "opencv2" "sensor_msgs" "std_msgs")
set(realsense_ting_controller_RUN_DEPENDS "message_runtime" "realsense2_camera" "rospy" "cv_bridge" "opencv2" "sensor_msgs" "std_msgs")
set(realsense_ting_controller_TEST_DEPENDS )
set(realsense_ting_controller_DOC_DEPENDS )
set(realsense_ting_controller_URL_WEBSITE "")
set(realsense_ting_controller_URL_BUGTRACKER "")
set(realsense_ting_controller_URL_REPOSITORY "")
set(realsense_ting_controller_DEPRECATED "")