// Generated by gencpp from file realsense_ting_controller/ImageCapture.msg
// DO NOT EDIT!


#ifndef REALSENSE_TING_CONTROLLER_MESSAGE_IMAGECAPTURE_H
#define REALSENSE_TING_CONTROLLER_MESSAGE_IMAGECAPTURE_H

#include <ros/service_traits.h>


#include <realsense_ting_controller/ImageCaptureRequest.h>
#include <realsense_ting_controller/ImageCaptureResponse.h>


namespace realsense_ting_controller
{

struct ImageCapture
{

typedef ImageCaptureRequest Request;
typedef ImageCaptureResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ImageCapture
} // namespace realsense_ting_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::realsense_ting_controller::ImageCapture > {
  static const char* value()
  {
    return "33ea4e5aeb30f5913da681ca459d55f3";
  }

  static const char* value(const ::realsense_ting_controller::ImageCapture&) { return value(); }
};

template<>
struct DataType< ::realsense_ting_controller::ImageCapture > {
  static const char* value()
  {
    return "realsense_ting_controller/ImageCapture";
  }

  static const char* value(const ::realsense_ting_controller::ImageCapture&) { return value(); }
};


// service_traits::MD5Sum< ::realsense_ting_controller::ImageCaptureRequest> should match
// service_traits::MD5Sum< ::realsense_ting_controller::ImageCapture >
template<>
struct MD5Sum< ::realsense_ting_controller::ImageCaptureRequest>
{
  static const char* value()
  {
    return MD5Sum< ::realsense_ting_controller::ImageCapture >::value();
  }
  static const char* value(const ::realsense_ting_controller::ImageCaptureRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::realsense_ting_controller::ImageCaptureRequest> should match
// service_traits::DataType< ::realsense_ting_controller::ImageCapture >
template<>
struct DataType< ::realsense_ting_controller::ImageCaptureRequest>
{
  static const char* value()
  {
    return DataType< ::realsense_ting_controller::ImageCapture >::value();
  }
  static const char* value(const ::realsense_ting_controller::ImageCaptureRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::realsense_ting_controller::ImageCaptureResponse> should match
// service_traits::MD5Sum< ::realsense_ting_controller::ImageCapture >
template<>
struct MD5Sum< ::realsense_ting_controller::ImageCaptureResponse>
{
  static const char* value()
  {
    return MD5Sum< ::realsense_ting_controller::ImageCapture >::value();
  }
  static const char* value(const ::realsense_ting_controller::ImageCaptureResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::realsense_ting_controller::ImageCaptureResponse> should match
// service_traits::DataType< ::realsense_ting_controller::ImageCapture >
template<>
struct DataType< ::realsense_ting_controller::ImageCaptureResponse>
{
  static const char* value()
  {
    return DataType< ::realsense_ting_controller::ImageCapture >::value();
  }
  static const char* value(const ::realsense_ting_controller::ImageCaptureResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // REALSENSE_TING_CONTROLLER_MESSAGE_IMAGECAPTURE_H
