// Generated by gencpp from file realsense_ting_controller/ImageCaptureResponse.msg
// DO NOT EDIT!


#ifndef REALSENSE_TING_CONTROLLER_MESSAGE_IMAGECAPTURERESPONSE_H
#define REALSENSE_TING_CONTROLLER_MESSAGE_IMAGECAPTURERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace realsense_ting_controller
{
template <class ContainerAllocator>
struct ImageCaptureResponse_
{
  typedef ImageCaptureResponse_<ContainerAllocator> Type;

  ImageCaptureResponse_()
    : response()  {
    }
  ImageCaptureResponse_(const ContainerAllocator& _alloc)
    : response(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _response_type;
  _response_type response;





  typedef boost::shared_ptr< ::realsense_ting_controller::ImageCaptureResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::realsense_ting_controller::ImageCaptureResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ImageCaptureResponse_

typedef ::realsense_ting_controller::ImageCaptureResponse_<std::allocator<void> > ImageCaptureResponse;

typedef boost::shared_ptr< ::realsense_ting_controller::ImageCaptureResponse > ImageCaptureResponsePtr;
typedef boost::shared_ptr< ::realsense_ting_controller::ImageCaptureResponse const> ImageCaptureResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::realsense_ting_controller::ImageCaptureResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::realsense_ting_controller::ImageCaptureResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::realsense_ting_controller::ImageCaptureResponse_<ContainerAllocator1> & lhs, const ::realsense_ting_controller::ImageCaptureResponse_<ContainerAllocator2> & rhs)
{
  return lhs.response == rhs.response;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::realsense_ting_controller::ImageCaptureResponse_<ContainerAllocator1> & lhs, const ::realsense_ting_controller::ImageCaptureResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace realsense_ting_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::realsense_ting_controller::ImageCaptureResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::realsense_ting_controller::ImageCaptureResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::realsense_ting_controller::ImageCaptureResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::realsense_ting_controller::ImageCaptureResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realsense_ting_controller::ImageCaptureResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realsense_ting_controller::ImageCaptureResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::realsense_ting_controller::ImageCaptureResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6de314e2dc76fbff2b6244a6ad70b68d";
  }

  static const char* value(const ::realsense_ting_controller::ImageCaptureResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6de314e2dc76fbffULL;
  static const uint64_t static_value2 = 0x2b6244a6ad70b68dULL;
};

template<class ContainerAllocator>
struct DataType< ::realsense_ting_controller::ImageCaptureResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "realsense_ting_controller/ImageCaptureResponse";
  }

  static const char* value(const ::realsense_ting_controller::ImageCaptureResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::realsense_ting_controller::ImageCaptureResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string response\n"
;
  }

  static const char* value(const ::realsense_ting_controller::ImageCaptureResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::realsense_ting_controller::ImageCaptureResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.response);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ImageCaptureResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::realsense_ting_controller::ImageCaptureResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::realsense_ting_controller::ImageCaptureResponse_<ContainerAllocator>& v)
  {
    s << indent << "response: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.response);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REALSENSE_TING_CONTROLLER_MESSAGE_IMAGECAPTURERESPONSE_H
