// Generated by gencpp from file realsense_ting_controller/ImgProcResponse.msg
// DO NOT EDIT!


#ifndef REALSENSE_TING_CONTROLLER_MESSAGE_IMGPROCRESPONSE_H
#define REALSENSE_TING_CONTROLLER_MESSAGE_IMGPROCRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace realsense_ting_controller
{
template <class ContainerAllocator>
struct ImgProcResponse_
{
  typedef ImgProcResponse_<ContainerAllocator> Type;

  ImgProcResponse_()
    : response()  {
    }
  ImgProcResponse_(const ContainerAllocator& _alloc)
    : response(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _response_type;
  _response_type response;





  typedef boost::shared_ptr< ::realsense_ting_controller::ImgProcResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::realsense_ting_controller::ImgProcResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ImgProcResponse_

typedef ::realsense_ting_controller::ImgProcResponse_<std::allocator<void> > ImgProcResponse;

typedef boost::shared_ptr< ::realsense_ting_controller::ImgProcResponse > ImgProcResponsePtr;
typedef boost::shared_ptr< ::realsense_ting_controller::ImgProcResponse const> ImgProcResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::realsense_ting_controller::ImgProcResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::realsense_ting_controller::ImgProcResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::realsense_ting_controller::ImgProcResponse_<ContainerAllocator1> & lhs, const ::realsense_ting_controller::ImgProcResponse_<ContainerAllocator2> & rhs)
{
  return lhs.response == rhs.response;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::realsense_ting_controller::ImgProcResponse_<ContainerAllocator1> & lhs, const ::realsense_ting_controller::ImgProcResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace realsense_ting_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::realsense_ting_controller::ImgProcResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::realsense_ting_controller::ImgProcResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::realsense_ting_controller::ImgProcResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::realsense_ting_controller::ImgProcResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realsense_ting_controller::ImgProcResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realsense_ting_controller::ImgProcResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::realsense_ting_controller::ImgProcResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7f7d5c92da2c60a9e1822680775d67aa";
  }

  static const char* value(const ::realsense_ting_controller::ImgProcResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7f7d5c92da2c60a9ULL;
  static const uint64_t static_value2 = 0xe1822680775d67aaULL;
};

template<class ContainerAllocator>
struct DataType< ::realsense_ting_controller::ImgProcResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "realsense_ting_controller/ImgProcResponse";
  }

  static const char* value(const ::realsense_ting_controller::ImgProcResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::realsense_ting_controller::ImgProcResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] response\n"
;
  }

  static const char* value(const ::realsense_ting_controller::ImgProcResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::realsense_ting_controller::ImgProcResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.response);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ImgProcResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::realsense_ting_controller::ImgProcResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::realsense_ting_controller::ImgProcResponse_<ContainerAllocator>& v)
  {
    s << indent << "response[]" << std::endl;
    for (size_t i = 0; i < v.response.size(); ++i)
    {
      s << indent << "  response[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.response[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // REALSENSE_TING_CONTROLLER_MESSAGE_IMGPROCRESPONSE_H
