// Generated by gencpp from file realsense_ting_controller/ImgProcRequest.msg
// DO NOT EDIT!


#ifndef REALSENSE_TING_CONTROLLER_MESSAGE_IMGPROCREQUEST_H
#define REALSENSE_TING_CONTROLLER_MESSAGE_IMGPROCREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace realsense_ting_controller
{
template <class ContainerAllocator>
struct ImgProcRequest_
{
  typedef ImgProcRequest_<ContainerAllocator> Type;

  ImgProcRequest_()
    : request()  {
    }
  ImgProcRequest_(const ContainerAllocator& _alloc)
    : request(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _request_type;
  _request_type request;





  typedef boost::shared_ptr< ::realsense_ting_controller::ImgProcRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::realsense_ting_controller::ImgProcRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ImgProcRequest_

typedef ::realsense_ting_controller::ImgProcRequest_<std::allocator<void> > ImgProcRequest;

typedef boost::shared_ptr< ::realsense_ting_controller::ImgProcRequest > ImgProcRequestPtr;
typedef boost::shared_ptr< ::realsense_ting_controller::ImgProcRequest const> ImgProcRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::realsense_ting_controller::ImgProcRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::realsense_ting_controller::ImgProcRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::realsense_ting_controller::ImgProcRequest_<ContainerAllocator1> & lhs, const ::realsense_ting_controller::ImgProcRequest_<ContainerAllocator2> & rhs)
{
  return lhs.request == rhs.request;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::realsense_ting_controller::ImgProcRequest_<ContainerAllocator1> & lhs, const ::realsense_ting_controller::ImgProcRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace realsense_ting_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::realsense_ting_controller::ImgProcRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::realsense_ting_controller::ImgProcRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::realsense_ting_controller::ImgProcRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::realsense_ting_controller::ImgProcRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realsense_ting_controller::ImgProcRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realsense_ting_controller::ImgProcRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::realsense_ting_controller::ImgProcRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9b13f31f7a0a36901919f7ec0d9f40d4";
  }

  static const char* value(const ::realsense_ting_controller::ImgProcRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9b13f31f7a0a3690ULL;
  static const uint64_t static_value2 = 0x1919f7ec0d9f40d4ULL;
};

template<class ContainerAllocator>
struct DataType< ::realsense_ting_controller::ImgProcRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "realsense_ting_controller/ImgProcRequest";
  }

  static const char* value(const ::realsense_ting_controller::ImgProcRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::realsense_ting_controller::ImgProcRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string request\n"
;
  }

  static const char* value(const ::realsense_ting_controller::ImgProcRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::realsense_ting_controller::ImgProcRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.request);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ImgProcRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::realsense_ting_controller::ImgProcRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::realsense_ting_controller::ImgProcRequest_<ContainerAllocator>& v)
  {
    s << indent << "request: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.request);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REALSENSE_TING_CONTROLLER_MESSAGE_IMGPROCREQUEST_H
