// Generated by gencpp from file realsense_ting_controller/ImgProc.msg
// DO NOT EDIT!


#ifndef REALSENSE_TING_CONTROLLER_MESSAGE_IMGPROC_H
#define REALSENSE_TING_CONTROLLER_MESSAGE_IMGPROC_H

#include <ros/service_traits.h>


#include <realsense_ting_controller/ImgProcRequest.h>
#include <realsense_ting_controller/ImgProcResponse.h>


namespace realsense_ting_controller
{

struct ImgProc
{

typedef ImgProcRequest Request;
typedef ImgProcResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ImgProc
} // namespace realsense_ting_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::realsense_ting_controller::ImgProc > {
  static const char* value()
  {
    return "27a3ac67f0bd767a8424b890cbe335fe";
  }

  static const char* value(const ::realsense_ting_controller::ImgProc&) { return value(); }
};

template<>
struct DataType< ::realsense_ting_controller::ImgProc > {
  static const char* value()
  {
    return "realsense_ting_controller/ImgProc";
  }

  static const char* value(const ::realsense_ting_controller::ImgProc&) { return value(); }
};


// service_traits::MD5Sum< ::realsense_ting_controller::ImgProcRequest> should match
// service_traits::MD5Sum< ::realsense_ting_controller::ImgProc >
template<>
struct MD5Sum< ::realsense_ting_controller::ImgProcRequest>
{
  static const char* value()
  {
    return MD5Sum< ::realsense_ting_controller::ImgProc >::value();
  }
  static const char* value(const ::realsense_ting_controller::ImgProcRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::realsense_ting_controller::ImgProcRequest> should match
// service_traits::DataType< ::realsense_ting_controller::ImgProc >
template<>
struct DataType< ::realsense_ting_controller::ImgProcRequest>
{
  static const char* value()
  {
    return DataType< ::realsense_ting_controller::ImgProc >::value();
  }
  static const char* value(const ::realsense_ting_controller::ImgProcRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::realsense_ting_controller::ImgProcResponse> should match
// service_traits::MD5Sum< ::realsense_ting_controller::ImgProc >
template<>
struct MD5Sum< ::realsense_ting_controller::ImgProcResponse>
{
  static const char* value()
  {
    return MD5Sum< ::realsense_ting_controller::ImgProc >::value();
  }
  static const char* value(const ::realsense_ting_controller::ImgProcResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::realsense_ting_controller::ImgProcResponse> should match
// service_traits::DataType< ::realsense_ting_controller::ImgProc >
template<>
struct DataType< ::realsense_ting_controller::ImgProcResponse>
{
  static const char* value()
  {
    return DataType< ::realsense_ting_controller::ImgProc >::value();
  }
  static const char* value(const ::realsense_ting_controller::ImgProcResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // REALSENSE_TING_CONTROLLER_MESSAGE_IMGPROC_H
