(cl:defpackage realsense_ting_controller-srv
  (:use )
  (:export
   "IMAGECAPTURE"
   "<IMAGECAPTURE-REQUEST>"
   "IMAGECAPTURE-REQUEST"
   "<IMAGECAPTURE-RESPONSE>"
   "IMAGECAPTURE-RESPONSE"
   "IMGPROC"
   "<IMGPROC-REQUEST>"
   "IMGPROC-REQUEST"
   "<IMGPROC-RESPONSE>"
   "IMGPROC-RESPONSE"
  ))

